name: carrot
description: Motivational App to achieve your goals

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^9.1.0
  english_words: ^4.0.0
  provider: ^6.0.0
  confetti: ^0.7.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications:
  intl:
  http:
  image_picker:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/front/assets/images/
    -  lib/front/assets/icons/